service: coronavirus-ok-api

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: us-east-1

  # These environment variables are made available to our functions
  # under process.env.
  environment:
    tableName: coronavirusTestResults

  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  # Defines an HTTP API endpoint that calls the main function in persistResult.js
  # - path: url path is /persistResult
  # - method: POST request
  # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
  #     domain api call
  # - authorizer: authenticate using the AWS IAM role
  persistResult:
    handler: persistResult.main
    events:
      - http:
          path: persistResult
          method: post
          cors: true
          # authorizer: aws_iam

  listResults:
    handler: listResults.main
    events:
      - http:
          path: listResults
          method: get
          cors: true

  listResultsByDate:
    handler: listResultsByDate.main
    events:
      - http:
          path: listResults/:date
          method: get
          cors: true

  scrapeResults:
    handler: scrapeResults.main
    events:
      - http:
          path: scrapeResults
          method: get
          cors: true

  testResultsWorker:
    handler: testResultsWorker.main
    events:
      - schedule:
          name: coronavirus-test-results-worker
          description: 'Crawls the OK Health Dept website and retrieves coronavirus test results'
          rate: rate(3 hours)